# Specifies the API version of the Kubernetes resource
apiVersion: v1
# Defines the type of Kubernetes resource (in this case, a Service)
kind: Service
# Metadata for the Service, including its name and other identifying information
metadata:
  # Name of the Service, used to identify it within the cluster
  name: mega-city-cab-service-backend
# Specification for the Service's desired state
spec:
  # Selector to match pods that this Service will route traffic to
  selector:
    # Label identifying the application pods to target
    app: mega-city-cab-service-backend
  # List of ports exposed by the Service
  ports:
    - # Protocol used for communication
      protocol: TCP
      # Port exposed by the Service for external access
      port: 80
      # Port on the target pods where the application is listening
      targetPort: 8080
  # Type of Service, determining how it is exposed
  type: LoadBalancer  # Exposes the Service externally using a cloud provider's load balancer