apiVersion: v1
kind: Service
metadata:
  name: mega-city-cab-service-backend
spec:
  selector:
    app: mega-city-cab-service-backend  # Same as app in deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Same as containerPort in deployment.yaml
  type: LoadBalancer  # Can be ClusterIP, NodePort, or LoadBalancer (for cloud)
