CREATE TABLE driver
(
    driver_registration_number SERIAL PRIMARY KEY,
    driver_first_name          VARCHAR(255)                  NOT NULL,
    driver_last_name           VARCHAR(255)                  NOT NULL,
    driver_nic                 VARCHAR(255)                  NOT NULL,
    phone_number               VARCHAR(255)                  NOT NULL,
    email_address              VARCHAR(255),
    license_number             VARCHAR(255)                  NOT NULL,
    license_expiry_date        DATE,
    driver_address             VARCHAR(255),
    vehicle_assigned           VARCHAR(255) DEFAULT 'FALSE',
    driver_status              VARCHAR(255) DEFAULT 'Active' NOT NULL,
    emergency_contact          VARCHAR(255),
    date_of_birth              DATE                          NOT NULL,
    date_of_joining            DATE
);

INSERT INTO driver (driver_first_name,
                    driver_last_name,
                    driver_nic,
                    phone_number,
                    email_address,
                    license_number,
                    license_expiry_date,
                    driver_address,
                    vehicle_assigned,
                    driver_status,
                    emergency_contact,
                    date_of_birth,
                    date_of_joining)
VALUES ('John',
        'Doe',
        'NIC12345678V',
        '0771234567',
        'john.doe@example.com',
        'LIC123456',
        '2027-12-31',
        '123 Main Street, Cityville',
        'FALSE',
        'Active',
        '0779876543',
        '1990-05-15',
        '2022-01-01'),
       ('Jane',
        'Smith',
        'NIC87654321V',
        '0777654321',
        'jane.smith@example.com',
        'LIC654321',
        '2026-06-30',
        '456 Elm Street, Townsville',
        'FALSE',
        'Active',
        '0771239874',
        '1992-08-25',
        '2023-03-15');
